"""Unit tests for the image worthiness gate (src/ingest/post_images.py).

The requirement being pinned is asymmetric: a decorative image reaching a
citation is a worse failure than an informative one being dropped. So the
tests care most about what gets REJECTED, and about the margin logic — the
part most likely to be tuned later, and the part where a sign error would
silently invert the whole gate.

Heuristics run against Pillow-generated images (no binary fixtures in git);
the classifier runs against stubbed vectors, so no model and no network are
involved anywhere in this file.
"""
from __future__ import annotations

import io

import numpy as np
import pytest

from src.ingest import post_images
from src.ingest.post_images import (DECORATIVE_PROMPTS, INFORMATIVE_PROMPTS,
                                    classify, judge, shape_is_junk, url_is_junk)


# ── Heuristics: hard drops, no model ─────────────────────────────────────────

@pytest.mark.parametrize("url", [
    "https://substackcdn.com/image/avatar/12345.png",
    "https://www.gravatar.com/avatar/abc",
    "https://img.shields.io/badge/build-passing.svg",
    "https://example.com/assets/og-image.jpg",
    "https://example.com/static/divider.png",
])
def test_a_url_that_announces_itself_is_dropped_before_download(url: str) -> None:
    assert url_is_junk(url)


@pytest.mark.parametrize("url", [
    "https://substackcdn.com/image/fetch/w_1456/chart.png",
    "https://example.com/uploads/2026/architecture.png",
])
def test_a_plausible_content_url_survives_the_url_layer(url: str) -> None:
    assert url_is_junk(url) == ""


@pytest.mark.parametrize("ref,base,expected", [
    # The case a real README exposed: nanoGPT writes ![](assets/nanogpt.jpg),
    # which without resolution dies as a fetch failure on every such post.
    ("assets/chart.png",
     "https://raw.githubusercontent.com/o/r/master/README.md",
     "https://raw.githubusercontent.com/o/r/master/assets/chart.png"),
    ("/img/chart.png", "https://blog.example.com/posts/scaling.md",
     "https://blog.example.com/img/chart.png"),
    # Absolute refs pass through untouched, base or no base.
    ("https://cdn.example.com/x.png", "https://blog.example.com/p.md",
     "https://cdn.example.com/x.png"),
    ("https://cdn.example.com/x.png", "", "https://cdn.example.com/x.png"),
])
def test_a_relative_image_ref_resolves_against_the_post_uri(
    ref: str, base: str, expected: str
) -> None:
    assert post_images.resolve(ref, base) == expected


def test_a_short_divider_strip_is_dropped_for_being_thin() -> None:
    """The common Substack divider — 1200x100. Both rules would reject it; the
    minimum-dimension check is simply the one that runs first, and the reason
    string says so."""
    assert "too small" in shape_is_junk(1200, 100, animated=False)


def test_a_wide_image_is_demoted_but_never_hard_dropped() -> None:
    """Measured on real posts: every image the aspect rule VETOED was a
    genuine figure — a horizontal number line at 4.8:1, a flow diagram at
    5.9:1. Wide raises the bar and lets the classifier decide, exactly as
    position 0 does."""
    assert shape_is_junk(1600, 300, animated=False) == ""   # no hard drop
    assert post_images.is_wide(1600, 300) is True
    assert post_images.is_wide(600, 400) is False


def test_a_wide_figure_survives_the_demotion_but_a_wide_strip_does_not() -> None:
    diagram = _vec(0.27, 0.05)   # the measured score of the real flow diagram
    filler = _vec(0.23, 0.05)    # clears the normal floor, not the raised one
    assert classify(diagram, _PROMPTS, hero=False, alt="", wide=True)[0] is True
    assert classify(filler, _PROMPTS, hero=False, alt="", wide=True)[0] is False
    assert classify(filler, _PROMPTS, hero=False, alt="", wide=False)[0] is True


def test_an_icon_is_dropped() -> None:
    assert "too small" in shape_is_junk(64, 64, animated=False)


def test_an_animated_gif_is_dropped() -> None:
    assert shape_is_junk(600, 400, animated=True) == "animated GIF"


def test_a_chart_shaped_image_clears_the_heuristics() -> None:
    assert shape_is_junk(600, 400, animated=False) == ""


def test_a_tracking_pixel_is_dropped() -> None:
    assert "too small" in shape_is_junk(1, 1, animated=False)


# ── The decode path, on real generated bytes ─────────────────────────────────

def _png(width: int, height: int) -> bytes:
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (width, height), (250, 250, 250))
    draw = ImageDraw.Draw(img)
    for x in range(0, width, max(8, width // 12)):   # gridlines, chart-ish
        draw.line([(x, 0), (x, height)], fill=(200, 200, 200))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def test_decoding_reports_the_original_shape_and_downscales() -> None:
    from src.config import THUMB_WIDTH

    jpeg, width, height, animated = post_images._to_jpeg(_png(1200, 800))
    assert (width, height) == (1200, 800)   # the ORIGINAL shape, for the rules
    assert animated is False
    assert jpeg.startswith(b"\xff\xd8")     # a JPEG, like every other thumbnail

    from PIL import Image
    assert Image.open(io.BytesIO(jpeg)).size[0] == THUMB_WIDTH


def test_a_narrow_banner_decodes_then_fails_a_shape_rule() -> None:
    """Decoding reports the ORIGINAL dimensions, so downscaling to THUMB_WIDTH
    cannot launder a divider past the shape rules."""
    _, width, height, animated = post_images._to_jpeg(_png(1200, 100))
    assert shape_is_junk(width, height, animated)


# ── The classifier margin logic, on stubbed vectors ──────────────────────────

_INFO_DIR = np.array([1.0, 0.0])
_DECO_DIR = np.array([0.0, 1.0])
_PROMPTS = {**{p: _INFO_DIR for p in INFORMATIVE_PROMPTS},
            **{p: _DECO_DIR for p in DECORATIVE_PROMPTS}}


def _vec(info: float, deco: float) -> np.ndarray:
    """A stand-in image vector whose cosine against each bank is exactly what
    the test names — the real ones are L2-normalized, so a dot IS a cosine."""
    return np.array([info, deco])


def test_a_clear_chart_is_kept() -> None:
    keep, cls, score = classify(_vec(0.30, 0.10), _PROMPTS, hero=False, alt="")
    assert keep and cls == "informative" and score == pytest.approx(0.30)


def test_a_clear_photograph_is_dropped() -> None:
    keep, cls, _ = classify(_vec(0.12, 0.31), _PROMPTS, hero=False, alt="")
    assert not keep and cls == "decorative"


def test_beating_decorative_is_not_enough_without_clearing_the_floor() -> None:
    """'Closer to a chart than to a photo' is a weaker claim than 'is a chart'.
    Both conditions exist for this case."""
    keep, _, _ = classify(_vec(0.15, 0.02), _PROMPTS, hero=False, alt="")
    assert not keep


def test_clearing_the_floor_is_not_enough_without_the_margin() -> None:
    """The mirror case: a high score on BOTH banks means the image is simply
    salient, not that it is informative."""
    keep, _, _ = classify(_vec(0.30, 0.295), _PROMPTS, hero=False, alt="")
    assert not keep


def test_a_hero_image_faces_a_higher_floor_but_is_not_vetoed() -> None:
    """The written-down decision: position 0 demotes, it never vetoes. The
    same borderline image is kept in the body and dropped as cover art —
    and a hero image that scores well still gets in."""
    borderline = _vec(0.24, 0.05)
    assert classify(borderline, _PROMPTS, hero=False, alt="")[0] is True
    assert classify(borderline, _PROMPTS, hero=True, alt="")[0] is False
    assert classify(_vec(0.40, 0.05), _PROMPTS, hero=True, alt="")[0] is True


def test_alt_text_naming_a_figure_relaxes_the_floor() -> None:
    borderline = _vec(0.24, 0.05)
    assert classify(borderline, _PROMPTS, hero=True, alt="")[0] is False
    assert classify(borderline, _PROMPTS, hero=True,
                    alt="chart of loss curves")[0] is True


def test_generic_alt_text_earns_nothing() -> None:
    borderline = _vec(0.24, 0.05)
    assert classify(borderline, _PROMPTS, hero=True, alt="image")[0] is False


# ── Best-effort by contract ──────────────────────────────────────────────────

def test_an_unreachable_image_returns_a_drop_verdict_not_an_exception() -> None:
    """The parse stage has no retries: one dead image URL must not cost a
    whole post. Every failure path here is a verdict, never a raise."""
    verdict = judge("https://example.invalid/nope.png")
    assert verdict.keep is False
    assert "fetch failed" in verdict.reason
    assert verdict.jpeg == b""


def test_undecodable_bytes_return_a_drop_verdict(monkeypatch) -> None:
    monkeypatch.setattr(post_images, "_fetch", lambda url: b"not an image")
    verdict = judge("https://example.com/x.png")
    assert verdict.keep is False and "undecodable" in verdict.reason


def test_a_classifier_outage_drops_rather_than_raises(monkeypatch) -> None:
    """An unreachable clip service degrades a post to text-only; it does not
    fail the ingest."""
    monkeypatch.setattr(post_images, "_fetch", lambda url: _png(600, 400))

    def _boom() -> dict:
        raise RuntimeError("clip service unreachable")

    monkeypatch.setattr(post_images, "prompt_bank", _boom)
    verdict = judge("https://example.com/chart.png")
    assert verdict.keep is False and "classifier unavailable" in verdict.reason


def test_a_dropped_image_never_carries_bytes_or_a_vector(monkeypatch) -> None:
    """A drop verdict must not smuggle a JPEG or an embedding downstream — the
    caller keys off `keep`, and either one riding along on a rejected verdict
    is an accident waiting."""
    monkeypatch.setattr(post_images, "_fetch", lambda url: _png(1200, 100))
    verdict = judge("https://example.com/banner.png")
    assert verdict.keep is False
    assert verdict.jpeg == b"" and verdict.vector is None


def test_a_kept_image_hands_back_the_vector_it_was_judged_on(monkeypatch) -> None:
    """The caller upserts THIS vector rather than re-embedding the same bytes,
    so what was classified and what was indexed cannot diverge."""
    monkeypatch.setattr(post_images, "_fetch", lambda url: _png(600, 400))
    monkeypatch.setattr(post_images, "prompt_bank", lambda: _PROMPTS)
    monkeypatch.setattr("src.rag.embeddings.embed_jpegs",
                        lambda jpegs: np.array([[0.30, 0.05]]))
    verdict = judge("https://example.com/chart.png")
    assert verdict.keep is True
    assert verdict.vector is not None
    assert list(verdict.vector) == [0.30, 0.05]
